packages:
  - "apps/*"
  - "packages/*"

catalog:
  next: ^16.0.10
  react: ^19.2.3
  react-dom: ^19.2.3
  typescript: ^5.9.2
  "@types/react": ^19.2.3
  "@types/react-dom": ^19.2.3
  "@types/node": ^24.10.4
